format_version: v1.0
type: UniqueComponent
attributes: {id: drvPlcPhy}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_PLC_BAND_IN_USE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: '2'}
  - type: Boolean
    attributes: {id: DRV_PLC_COUP_G3_HIGH_ATTENUATION}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_PLC_COUP_G3_MULTIBAND}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: DRV_PLC_DEPENDENCY_DMA_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_EXT_INT_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '104'}
  - type: String
    attributes: {id: DRV_PLC_EXT_INT_PIO_PORT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: PIO_PORT_D}
  - type: String
    attributes: {id: DRV_PLC_EXT_INT_SRC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: PIOD_IRQn}
  - type: Combo
    attributes: {id: DRV_PLC_G3_BAND}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: FCC}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_LDO_EN_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '74'}
  - type: String
    attributes: {id: DRV_PLC_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: SPI0}
  - type: Integer
    attributes: {id: DRV_PLC_RX_DMA_CHANNEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: '0'}
  - type: Boolean
    attributes: {id: DRV_PLC_SLEEP_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_STBY_PIN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_THMON_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: Integer
    attributes: {id: DRV_PLC_TX_DMA_CHANNEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: '1'}
  - type: Boolean
    attributes: {id: DRV_PLC_TX_RX_DMA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: 'true'}
  - type: File
    attributes: {id: PLC_SOURCE_BIN_G3_CENA}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: PLC_SOURCE_BIN_G3_FCC}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_plc_phy_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: spi0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SPI0_SPI}
- type: ElementPosition
  attributes: {x: '592', y: '395', id: drvPlcPhy}
