configName: sam_d20_xpro_pl460
folderName: sam_d20_xpro_pl460
format_version: v1.0
frameworkPath: C:\0_CHRIS\Proyectos\03_MCHP_Harmony_3\BitBucket
processor: ATSAMD20J18
projectName: sam_d20_xpro_pl460
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMD20_DFP\3.6.112
