format_version: v1.0
type: UniqueComponent
attributes: {id: drv_usbhs_v1}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: USB_SPEED}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Full Speed}
- type: ElementPosition
  attributes: {x: '38', y: '336', id: drv_usbhs_v1}
