format_version: v1.0
type: UniqueComponent
attributes: {id: srv_pvddmon}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SRV_PVDDMON_ADC_CHANNEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Long
    attributes: {id: SRV_PVDDMON_HIGH_TH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '13'}
  - type: String
    attributes: {id: SRV_PVDDMON_HIGH_THRESHOLD_HEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pvddmon, value: '0xdb3'}
  - type: Long
    attributes: {id: SRV_PVDDMON_LOW_TH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: String
    attributes: {id: SRV_PVDDMON_LOW_THRESHOLD_HEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pvddmon, value: '0xa8a'}
- type: ElementPosition
  attributes: {x: '582', y: '211', id: srv_pvddmon}
