configName: sam_e70_xpld_pl460_cen_a
folderName: sam_e70_xpld_pl460_cen_a
format_version: v1.0
frameworkPath: ..\..\..\..
processor: ATSAME70Q21B
projectName: sam_e70_xpld_pl460_cen_a
settings:
  PackageFilter: bsp;core;core_apps_sam_e70_s70_v70_v71;core_apps_sam_g55;csp;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_g55;mbed_os_rtos;mbed_os_rtos_apps;net;net_apps_sam_e70_v71;smartenergy;smartenergy_g3;smartenergy_g3_apps;smartenergy_prime;smartenergy_prime_apps;usb_apps_device;wireless
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.5.86\same70b\atdf\ATSAME70Q21B.atdf
