format_version: v1.0
type: GeneratorComponent
attributes: {id: srv_usi}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SRV_USI_CDC_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_usi, value: 'false'}
  - type: Integer
    attributes: {id: SRV_USI_NUM_CDC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_usi, value: '0'}
  - type: Integer
    attributes: {id: SRV_USI_NUM_USART}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_usi, value: '1'}
  - type: Boolean
    attributes: {id: SRV_USI_USART_API}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_usi_0, value: 'true'}
  - type: File
    attributes: {id: SRV_USI_USART_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SRV_USI_USART_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: srv_usi}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: SRV_USI_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: srv_usi_0, value: USART1}
      - type: String
        attributes: {id: SRV_USI_DEVICE_SET}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: srv_usi_0, value: UART}
      - type: Integer
        attributes: {id: SRV_USI_USART_API_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: srv_usi, value: '0'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: srv_usi_USART_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usart1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: USART1_UART}
- type: ElementPosition
  attributes: {x: '214', y: '310', id: srv_usi}
