format_version: v1.0
type: UniqueComponent
attributes: {id: sys_time}
children:
- type: Symbols
  children:
  - type: Comment
    attributes: {id: SYS_TIME_ACHIEVABLEE_TICK_RATE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: 'Achievable Tick Rate Resolution (ms):0.999253337921ms'}
  - type: Long
    attributes: {id: SYS_TIME_ACHIEVABLE_TICK_RATE_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_time, value: '100074722'}
  - type: Combo
    attributes: {id: SYS_TIME_OPERATING_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: SYS_TIME_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_time, value: TC0}
  - type: String
    attributes: {id: SYS_TIME_REMOTE_COMPONENT_ID}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_time, value: tc0}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: sys_time_TMR_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tc0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: TC0_TMR}
- type: ElementPosition
  attributes: {x: '214', y: '144', id: sys_time}
