package:
  format-version: "1.0.0"
  name: "smartenergy_g3_apps"
  version: "v1.1.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.17.0"
    - name: "csp"
      type: "package"
      version: "v3.18.2"
    - name: "core"
      type: "package"
      version: "v3.13.2"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "smartenergy"
      type: "package"
      version: "dev"
    - name: "smartenergy_g3"
      type: "package"
      version: "dev"
    - name: "usb"
      type: "package"
      version: "v3.12.0"
    - name: "crypto"
      type: "package"
      version: "v3.8.0"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "net"
      type: "package"
      version: "v3.11.0"
    - name: "gfx"
      type: "package"
      version: "v3.13.0"
    - name: "wireless_15_4_phy"
      type: "package"
      version: "v1.1.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.2.0"