package:
  format-version: "1.0.0"
  name: "smartenergy_g3_apps"
  version: "v1.0.0"
  type: "application"
  status: "production"
  required: true

  dependencies:
    - name: "bsp"
      type: "package"
      version: "dev"
    - name: "csp"
      type: "package"
      version: "dev"
    - name: "core"
      type: "package"
      version: "dev"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "v10.5.1"
    - name: "smartenergy"
      type: "package"
      version: "dev"
    - name: "smartenergy_g3"
      type: "package"
      version: "dev"
    - name: "usb"
      type: "package"
      version: "dev"
    - name: "crypto"
      type: "package"
      version: "dev"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "net"
      type: "package"
      version: "dev"