package:
  format-version: "1.0.0"
  name: "smartenergy_g3_apps"
  version: "v1.2.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy_g3"
      type: "package"
      version: "v1.1.0"
    - name: "crypto_v4"
      type: "package"
      version: "v4.0.0-E3"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0"
    - name: "smartenergy_metrology"
      type: "package"
      version: "v2.0.0"
    - name: "usb"
      type: "package"
      version: "v3.16.0"
    - name: "shd"
      type: "package"
      version: "v1.3.0"