package:
  format-version: "1.0.0"
  name: "smartenergy_g3_apps"
  version: "v1.1.1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.5"
    - name: "smartenergy_g3"
      type: "package"
      version: "v1.0.1"
    - name: "usb"
      type: "package"
      version: "v3.12.0"
    - name: "crypto"
      type: "package"
      version: "v4.0.0-E1"
    - name: "net"
      type: "package"
      version: "v3.12.0"
    - name: "gfx"
      type: "package"
      version: "v3.13.0"
    - name: "wireless_15_4_phy"
      type: "package"
      version: "v1.1.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "v1.2.0"