format_version: v1.0
type: UniqueComponent
attributes: {id: srv_pcoup}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: SRV_PCOUP_AUX_G3_BAND}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: None}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '8480'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '265420804'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_11}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '853'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_12}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '251658240'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_13}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '1057008'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_14}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '853'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_15}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '251658240'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_16}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '1057023'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '1855'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '16191'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '819'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '2696675583'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '421075225'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_8}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '8224'}
  - type: Hex
    attributes: {id: SRV_PCOUP_DACC_9}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '68'}
  - type: Integer
    attributes: {id: SRV_PCOUP_GAIN_HIGH_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '248'}
  - type: Integer
    attributes: {id: SRV_PCOUP_GAIN_HIGH_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '119'}
  - type: Integer
    attributes: {id: SRV_PCOUP_GAIN_HIGH_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '496'}
  - type: Integer
    attributes: {id: SRV_PCOUP_GAIN_VLOW_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '701'}
  - type: Integer
    attributes: {id: SRV_PCOUP_GAIN_VLOW_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '350'}
  - type: Integer
    attributes: {id: SRV_PCOUP_GAIN_VLOW_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '883'}
  - type: Integer
    attributes: {id: SRV_PCOUP_LINE_DRIVER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Combo
    attributes: {id: SRV_PCOUP_MAIN_G3_BAND}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: CEN-B}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_HIGH_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '1133'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_HIGH_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '793'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_HIGH_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '559'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_HIGH_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '396'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_HIGH_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '280'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_HIGH_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '199'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_HIGH_6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '143'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_HIGH_7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '108'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_VLOW_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '2871'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_VLOW_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '2120'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_VLOW_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '1498'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_VLOW_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '1054'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_VLOW_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '740'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_VLOW_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '519'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_VLOW_6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '366'}
  - type: Integer
    attributes: {id: SRV_PCOUP_RMS_VLOW_7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '259'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '471'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_11}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '334'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_12}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '238'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_13}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '169'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_14}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '122'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_15}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '90'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_8}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '950'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_HIGH_9}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '667'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '1935'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_11}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '1362'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_12}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '965'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_13}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '686'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_14}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '493'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_15}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '353'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_7}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '0'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_8}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '3878'}
  - type: Integer
    attributes: {id: SRV_PCOUP_THRS_VLOW_9}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pcoup, value: '2749'}
- type: ElementPosition
  attributes: {x: '588', y: '221', id: srv_pcoup}
