format_version: v1.0
configName: pic32cxmtg
folderName: pic32cxmtg_ek
frameworkPath: C:\H3_repos
processor: PIC32CX2051MTG128
projectName: pic32cxmtg_ek
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CX-MT_DFP\1.1.115\PIC32CX-MTG\atdf\PIC32CX2051MTG128.atdf
