configName: pic32cxmtg
folderName: pic32cxmtg_ek
format_version: v1.0
frameworkPath: C:\H3_repos
processor: PIC32CX2051MTG128
projectName: pic32cxmtg_ek
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CX-MT_DFP\1.3.132
