format_version: v1.0
configName: wbz451_curiosity_pl460_freertos
folderName: wbz451_curiosity_pl460_freertos
frameworkPath: C:\0_CHRIS\Proyectos\03_MCHP_Harmony_3\BitBucket
processor: WBZ451
projectName: wbz451_curiosity_pl460_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CX-BZ_DFP\1.0.107\WBZ451\atdf\WBZ451.atdf
