configName: pic32cx_mtsh_db_pl460
folderName: pic32cx_mtsh_db_pl460
format_version: v1.0
frameworkPath: C:\WORK\GIT\mh3
processor: PIC32CX2051MTSH128
projectName: pic32cx_mtsh_db_pl460
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CX-MT_DFP\1.3.132
