configName: sam_e70_xult_pl460_freertos
folderName: sam_e70_xult_pl460_freertos
format_version: v1.0
frameworkPath: C:\WORK\GIT\mh3
processor: ATSAME70Q21B
projectName: sam_e70_xult_pl460_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAME70_DFP\4.10.248
