configName: pic32cx_mtg_ek_pl460_rf215_freertos
folderName: pic32cx_mtg_ek_pl460_rf215_freertos
format_version: v1.0
frameworkPath: C:\WORK\GIT\mh3
processor: PIC32CX2051MTG128
projectName: pic32cx_mtg_ek_pl460_rf215_freertos
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CX-MT_DFP\1.3.132
