format_version: v1.0
configName: sam_e70_xult_pl460
folderName: sam_e70_xult_pl460
frameworkPath: C:\0_CHRIS\Proyectos\03_MCHP_Harmony_3\BitBucket
processor: ATSAME70Q21B
projectName: sam_e70_xult_pl460
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME70_DFP\4.7.108\same70b\atdf\ATSAME70Q21B.atdf
