configName: sam_e70_xult_pl460
folderName: sam_e70_xult_pl460
format_version: v1.0
frameworkPath: C:\0_CHRIS\Proyectos\03_MCHP_Harmony_3\BitBucket
processor: ATSAME70Q21B
projectName: g3_mac_rt_plc_and_go_sam_e70_xult_pl460
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: SAME70_DFP\4.10.248
