format_version: v1.0
type: UniqueComponent
attributes: {id: drvPlcPhy}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_PLC_BAND_IN_USE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: '1'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_CD_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '43'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_EXT_INT_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '24'}
  - type: String
    attributes: {id: DRV_PLC_EXT_INT_PIO_PORT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: PIO_PORT_A}
  - type: String
    attributes: {id: DRV_PLC_EXT_INT_SRC}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: PIOA_IRQn}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_LDO_EN_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '23'}
  - type: String
    attributes: {id: DRV_PLC_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: FLEXCOM5}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_RESET_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_STBY_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '42'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_THMON_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '29'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_plc_phy_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: flexcom5}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: FLEXCOM5_SPI}
- type: ElementPosition
  attributes: {x: '638', y: '348', id: drvPlcPhy}
