format_version: v1.0
type: UniqueComponent
attributes: {id: srv_psniffer}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: SRV_PSNF_PLC_PROFILE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_psniffer, value: '1'}
- type: ElementPosition
  attributes: {x: '387', y: '189', id: srv_psniffer}
