format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PL360G55CB_Evaluation_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '23', y: '73', id: BSP_PL360G55CB_Evaluation_Kit}
