configVersion: 1.0.0
componentName: g3_config
coreVersion: 5.8.3
device: ATSAMD20J18
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyModule
  name: g3_config
  type: module
  version: ''
- dependencyPackage: ''
  devMode: true
  name: smartenergy_g3
  type: package
  version: v1.1.0
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments:
    children:
    - children:
      - attributes:
          id: g3_palplc_dependency
        children:
        - children:
          - attributes:
              id: enabled
            children:
            - type: Value
              value: 'true'
            type: Boolean
          type: Attributes
        type: GenericDependency
      - attributes:
          id: g3_srv_log_report_dependency
        children:
        - children:
          - attributes:
              id: enabled
            children:
            - type: Value
              value: 'true'
            type: Boolean
          type: Attributes
        type: GenericDependency
      - attributes:
          id: g3_srv_queue_dependency
        children:
        - children:
          - attributes:
              id: enabled
            children:
            - type: Value
              value: 'true'
            type: Boolean
          type: Attributes
        type: GenericDependency
      - attributes:
          id: g3_srv_random_dependency
        children:
        - children:
          - attributes:
              id: enabled
            children:
            - type: Value
              value: 'true'
            type: Boolean
          type: Attributes
        type: GenericDependency
      - attributes:
          id: g3_srv_security_dependency
        children:
        - children:
          - attributes:
              id: enabled
            children:
            - type: Value
              value: 'true'
            type: Boolean
          type: Attributes
        type: GenericDependency
      type: Attachments
    type: g3_config
  elementPosition:
    attributes:
      id: G3 STACK
    children:
    - children:
      - attributes:
          id: g3_config
          x: '20'
          y: '41'
        type: ElementPosition
      type: ElementPositions
    type: ComponentGraph
  symbols:
    ADP_BLACKLIST_TABLE_SIZE:
      attributes:
        id: ADP_BLACKLIST_TABLE_SIZE
      children:
      - children:
        - attributes:
            value: '10'
          type: User
        type: Values
      type: Integer
    ADP_PRESENT:
      attributes:
        id: ADP_PRESENT
      children:
      - children:
        - attributes:
            id: g3_config
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    ADP_ROUTING_SET_SIZE:
      attributes:
        id: ADP_ROUTING_SET_SIZE
      children:
      - children:
        - attributes:
            value: '10'
          type: User
        type: Values
      type: Integer
    ADP_ROUTING_TABLE_SIZE:
      attributes:
        id: ADP_ROUTING_TABLE_SIZE
      children:
      - children:
        - attributes:
            value: '20'
          type: User
        type: Values
      type: Integer
    G3_COORDINATOR:
      attributes:
        id: G3_COORDINATOR
      children:
      - children:
        - attributes:
            id: g3_config
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
    G3_DEVICE:
      attributes:
        id: G3_DEVICE
      children:
      - children:
        - attributes:
            id: g3_config
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    G3_MODE:
      attributes:
        id: G3_MODE
      children:
      - children:
        - attributes:
            value: G3 Stack (ADP + MAC) PLC
          type: User
        type: Values
      type: Combo
    G3_ROLE:
      attributes:
        id: G3_ROLE
      children:
      - children:
        - attributes:
            id: visible
          children:
          - type: Value
            value: 'true'
          type: Boolean
        type: Attributes
      - children:
        - attributes:
            value: PAN Device
          type: User
        type: Values
      type: Combo
    MAC_PLC_DEVICE_TABLE_SIZE:
      attributes:
        id: MAC_PLC_DEVICE_TABLE_SIZE
      children:
      - children:
        - attributes:
            value: '64'
          type: User
        type: Values
      type: Integer
    MAC_PLC_PRESENT:
      attributes:
        id: MAC_PLC_PRESENT
      children:
      - children:
        - attributes:
            id: g3_config
            value: 'true'
          type: Dynamic
        type: Values
      type: Boolean
    MAC_RF_PRESENT:
      attributes:
        id: MAC_RF_PRESENT
      children:
      - children:
        - attributes:
            id: g3_config
            value: 'false'
          type: Dynamic
        type: Values
      type: Boolean
  userData: {}
