format_version: v1.0
type: UniqueComponent
attributes: {id: srv_pvddmon}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SRV_PVDDMON_ADC_CHANNEL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
- type: ElementPosition
  attributes: {x: '417', y: '247', id: srv_pvddmon}
