format_version: v1.0
type: UniqueComponent
attributes: {id: srv_pserial}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: SRV_PSER_PLC_PROFILE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: srv_pserial, value: '2'}
- type: ElementPosition
  attributes: {x: '607', y: '265', id: srv_pserial}
