format_version: v1.0
type: UniqueComponent
attributes: {id: drvPlcPhy}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DRV_PLC_BAND_IN_USE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: '1'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_CD_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
  - type: Comment
    attributes: {id: DRV_PLC_DEPENDENCY_DMA_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_LDO_EN_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '74'}
  - type: String
    attributes: {id: DRV_PLC_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: SPI0}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_RESET_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: DRV_PLC_RX_DMA_CHANNEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: '0'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_STBY_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: KeyValueSet
    attributes: {id: DRV_PLC_THMON_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '61'}
  - type: Integer
    attributes: {id: DRV_PLC_TX_DMA_CHANNEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: '1'}
  - type: Boolean
    attributes: {id: DRV_PLC_TX_RX_DMA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPlcPhy, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_plc_phy_SPI_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: spi0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SPI0_SPI}
- type: ElementPosition
  attributes: {x: '598', y: '289', id: drvPlcPhy}
