configName: wbz451_curiosity_pl460
folderName: phy_tester_tool_wbz451_curiosity_pl460
format_version: v1.0
frameworkPath: C:\0_CHRIS\Proyectos\03_MCHP_Harmony_3\BitBucket
processor: WBZ451
projectName: g3_phy_tester_tool_wbz451_curiosity_pl460
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: PIC32CX-BZ_DFP\1.3.238
